# === Server Port ===
#server.port=8080

# === Database (Only My Local PostgreSQL) ===
spring.datasource.url=jdbc:postgresql://localhost:5432/tripick_db
spring.datasource.username=postgres
spring.datasource.password=0000!
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA(Hibernate) ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === JWT ===
jwt.secret=aaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbnbfvjhsgfdjasjdfgaksjhgdkjahsdkjahskjdhakhdalgwiulghql

# === Kakao Map API (???? ?) ===
kakaomap.api.key=a59e4af97a0715d551be2349e7096e87
kakao.api.base-url=https://dapi.kakao.com
